version: '3'
services:
  redis:
    image: redis
    networks:
      - app-network
    ports:
      - 6379:6379
  app:
    image: 
    container_name: app
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email arjunudo@gmail.com --agree-tos --no-eff-email --staging -d api-dev.wisebox.xyz

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /Users/arjun/core/docker/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /Users/arjun/core/docker//dhparam/
      o: bind

networks:
  app-network:
    driver: bridge